version: '3.9'
services:
  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: astro-app #project name
    volumes:
      - ../app:/usr/src/app
    ports:
      - "4321:4321"
    stdin_open: true
    tty: true
